name: NoSQL Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python nosql50/mongo.py

      - name: Set exit status
        id: set_status
        run: exit 0

      - name: Update README if tests pass
        run: |
          if [ "${{ steps.set_status.outcome }}" == 'success' ]; then
            echo 'Tests passing' > README.md
          else
            echo 'Tests failed' > README.md
          fi
        if: always()
